#!/usr/bin/env bash

# Adds the license summary to the top of any .py file that is (1) tracked by
# git and (2) doesn't already have the header.

cd `git rev-parse --show-toplevel`

python_files=`git ls-files | grep '\.py$'`
copyright_line=`head -1 tools/license_header`

for f in `grep -L "$copyright_line" $python_files`
do
    echo "Adding license header to $f"
    dest="$f.with_header"
    cat tools/license_header $f > $dest
    mv $dest $f
done
